(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_NP_", frames: [[322,0,95,171],[229,482,190,139],[322,173,99,127],[0,482,227,206],[0,0,320,480]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.fourteencookiebottomleft = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.fourteencookietopleft = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.fourteencookietopright = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.fourteenpiebottomleft = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.seventeenberries = function() {
	this.initialize(img.seventeenberries);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,86,95);


(lib.seventeentable = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whiterectanglefadeone = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgaKAmmMAAAhNLMA0VAAAMAAABNLg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiterectanglefadeone, new cjs.Rectangle(-167.4,-246.9,335,494), null);


(lib.swetinspiration = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AhrBtQgLgEAAgKQAAgHALgEIAGgCQAFgDADgIQACgHAAgRIAAgPIAAgRIAAgWQAAgigCgLQgCgKgEgCIgKgFQgOgDAAgIQAAgFAFgDQAEgEAJgEIAfgKIAXgEQAGAAADAEQADACAAAIIAAAPIAAACIABAAIACAAIAAgBIAGgFIAEgDQAYgXAbAAQAPAAAPAHQAPAGAKAMQAKANAEAQQAEAQAAAkIAAAcIAAAPIAAAMQAAAQACAGQACAHAGADIAFACQALAEAAAHQAAAKgKAEQgKACgiAAQgfAAgKgCQgKgEAAgIQAAgIALgFIAIgDQAFgDACgKQACgJAAgXQAAhFgJgSQgJgSgXAAQgLAAgKAIQgLAHgGALQgEAKgCARQgCAQAAArQAAAVACAIQABAGAFADIAIADQALAFAAAIQAAAIgKAEQgLADgdAAQghAAgLgDg");
	this.shape.setTransform(94.8,26.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhPBSQgfggAAgxQAAgxAhggQAgghAxAAQAvAAAeAfQAeAeAAAxQAAAxggAiQghAigvAAQgvAAgfgggAgphAQgOARAAAdQAAArATAdQATAdAZAAQAVABANgTQAOgSAAgdQAAgqgTgdQgTgegZABQgVgBgNATg");
	this.shape_1.setTransform(69.6,26.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgmCcQgLgDAAgKQAAgHALgEIAGgDQAFgDADgHQACgHAAgRIgBgPIAAgRIAAgXQAAgigBgKQgCgKgFgDIgKgEQgNgEAAgHQAAgFAEgEQAFgEAIgDIAhgLIAXgEQAGAAADAEQACAEAAAKIAAANIAAAKIgCA3IAAABIgBA2QAAAVACAIQACAJAFADIAIADQALAEAAAJQAAAIgKADQgLAEgdAAQggAAgLgEgAgahtQgKgIABgLQgBgNALgJQAKgJAPAAQANAAAJAIQAKAIAAAMQAAAMgLAJQgKAIgOAAQgOAAgJgHg");
	this.shape_2.setTransform(51,21.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgLCDQgLgDgIgHQgHgIgEgMQgDgMAAggIAAh1IgUAAIgGgBIgCgGIAAgFQAAgHAXgUIAJgHIAIgIQAXgUAIAAIAGACQADACAAADIAAApIAxAAQAFAAACACQACACAAAGIAAAGQAAAFgCADQgCACgFAAIgtAAIgEACIgBAGIAABrQAAAcAFAIQAEAGANABQAHAAALgEIAPgDQAFAAADACQADADAAAFQAAAMgSALQgTALgYAAQgMAAgLgEg");
	this.shape_3.setTransform(37.2,24.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAnBnIgMgMIgJAFQgbASgbAAQggAAgTgSQgUgTAAgeQAAgjAZgTQAagTAtAAQALAAAFADQAGADAAAJQAAAMgPAAQgVAAgOAKQgNALAAASQAAASAMAKQALALATAAQAVAAAJgKQAJgJAAgXIAAhTQAAgTgIgKQgJgLgOAAQgLAAgJAFQgJAFgJAKIgFAFQgNARgPAAQgIAAgFgFQgGgGAAgJQAAgVAagOQAZgOAoAAQAXAAASAGQARAHAKAMQAGAIADAOQADANAAAfIAABGQAAAMACAGQACAGAEACIAHACQAOADAAAIQAAAKgPAJQgOAIgUAAQgKAAgKgLg");
	this.shape_4.setTransform(18,26.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhBBtQgLgEAAgKQAAgHAKgEIAGgCQAGgDACgIQACgHAAgRIAAgPIAAgRIAAgNQAAgngCgNQgCgMgEgCIgKgFQgNgDAAgIQAAgFAEgDQAEgEAJgEIAegKIATgDQALAAADAdIABAEIABABQALgRANgKQAMgJAMAAQAPAAAJAJQAJAKAAAOQAAAQgHAJQgGAJgNAAIgLgCIgJgHIgFgJQgCgFgDgBQgPAAgGAWQgFAUAABCQAAATACAJQACAKAGADIAJADQANAEAAAJQAAAIgMAEQgMADgeAAQghAAgKgDg");
	this.shape_5.setTransform(-1.8,26.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgmCcQgLgDAAgKQAAgHALgEIAGgDQAFgDADgHQACgHAAgRIgBgPIAAgRIAAgXQAAgigBgKQgCgKgFgDIgKgEQgNgEAAgHQAAgFAEgEQAFgEAIgDIAhgLIAXgEQAGAAADAEQACAEAAAKIAAANIAAAKIgCA3IAAABIgBA2QAAAVACAIQACAJAFADIAIADQALAEAAAJQAAAIgKADQgLAEgdAAQggAAgLgEgAgahtQgKgIABgLQgBgNALgJQAKgJAPAAQANAAAJAIQAKAIAAAMQAAAMgLAJQgKAIgOAAQgOAAgJgHg");
	this.shape_6.setTransform(-17,21.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhqCVQgLgEAAgJQAAgHAJgEIAMgFQAEgFACgRQABgRAAg3IAAgiQAAg8gCgRQgBgRgGgDIgKgEQgNgEABgIQgBgFAEgEQAEgDAJgEIAfgKQAOgDAIAAQAGAAADADQACADABAIIAAALIAAAEIABABIAJgGIAIgGQANgKAMgFQAMgFANAAQApAAAaAeQAZAeABAvQAAA0gdAiQgeAhgsAAQgTAAgHgFQgHgFAAgJQAAgFADgDQAEgEAHAAIAFABIAIABQAYAAAOgUQAPgUAAgiQAAglgQgWQgQgYgZAAQgWAAgNANQgNANAAAhIAACKIABAWQACAJACADQADADAKACIAIADIAFAEIABAHQAAAIgMADQgNAEgfAAQggAAgLgEg");
	this.shape_7.setTransform(-36.6,30.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgQByIgXgEIgHAEIgGABIgFgBIgEgDQgIgGgGgSQgGgSAAgQQAAgHAEgEQADgFAGAAQAKAAAKASIAJANQAGAIAMAFQALAFAMAAQAOAAAJgHQAIgHAAgMQAAgTgkgRIgMgGQgigRgMgOQgMgOAAgVQAAgcATgSQAUgSAgAAIAPABIAPACIAKgEIAHgBQALAAAKARQAKASAAASQAAAIgDAFQgEAEgGAAQgFAAgFgEQgFgEgGgLQgIgNgJgGQgJgFgMAAQgMAAgIAHQgHAHAAAMQAAAKAIAHQAHAIAbAOIACABQA9AdAAAjQAAAfgXAUQgYAVgjAAg");
	this.shape_8.setTransform(-58.5,26.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AhrBtQgLgEAAgKQAAgHALgEIAGgCQAFgDADgIQACgHAAgRIAAgPIAAgRIAAgWQAAgigCgLQgCgKgEgCIgKgFQgOgDAAgIQAAgFAFgDQAEgEAJgEIAfgKIAXgEQAGAAADAEQADACAAAIIAAAPIAAACIABAAIACAAIAAgBIAGgFIAEgDQAYgXAbAAQAPAAAPAHQAPAGAKAMQAKANAEAQQAEAQAAAkIAAAcIAAAPIAAAMQAAAQACAGQACAHAGADIAFACQALAEAAAHQAAAKgKAEQgKACgiAAQgfAAgKgCQgKgEAAgIQAAgIALgFIAIgDQAFgDACgKQACgJAAgXQAAhFgJgSQgJgSgXAAQgLAAgKAIQgLAHgGALQgEAKgCARQgCAQAAArQAAAVACAIQABAGAFADIAIADQALAFAAAIQAAAIgKAEQgLADgdAAQghAAgLgDg");
	this.shape_9.setTransform(-80.9,26.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgtCaQgNgEAAgJQAAgJAOgFIAKgFQAEgEACgaQACgaAAhEIgBhSQgCgggDgEQgCgDgMgFQgMgFAAgJQAAgIAKgDQAKgEAmAAQAnAAAKADQAKAEAAAIQAAAJgOAFIgJAFQgFADgBAWIgCBIIABBoQACAmADAEQACADALAEQAMAFAAAJQAAAJgMAEQgMAEgjAAQghAAgMgEg");
	this.shape_10.setTransform(-100.9,21.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgLCDQgLgDgIgHQgHgHgEgMQgDgMAAghIAAh0IgUAAIgGgCIgCgGIAAgFQAAgIAXgTIAJgHIAIgIQAXgUAIAAIAGACQADACAAADIAAApIAxAAQAFAAACACQACADAAAFIAAAGQAAAGgCACQgCACgFABIgtAAIgEABIgBAGIAABrQAAAcAFAIQAEAGANAAQAHABALgEIAPgDQAFAAADADQADACAAAFQAAAMgSALQgTALgYAAQgMAAgLgEg");
	this.shape_11.setTransform(53.8,-27.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AhHBSQgfgfAAgwQAAgyAgghQAgghAxAAQAqAAAZAYQAZAYAAApQAAANgEAFQgEAEgRAAIhTAAQgHAAgEgEQgEgDAAgGQAAgGAEgDQAEgDAHAAIAtAAIALgBQADgCAAgFQAAgVgOgOQgPgPgTAAQgaAAgNAXQgMAXAAAgQAAAhARAZQARAZAbgBQAQABAMgEQALgDAKgIIAIgGQALgJAGAAQAFAAADADQADADAAAFQAAAFgFAIQgGAIgJAGQgTAQgSAIQgRAGgVAAQguAAgfggg");
	this.shape_12.setTransform(34.4,-25.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AhHBSQgfgfAAgwQAAgyAgghQAgghAxAAQAqAAAZAYQAZAYAAApQAAANgEAFQgEAEgRAAIhTAAQgHAAgEgEQgEgDAAgGQAAgGAEgDQAEgDAHAAIAtAAIALgBQADgCAAgFQAAgVgOgOQgPgPgTAAQgaAAgNAXQgMAXAAAgQAAAhARAZQARAZAbgBQAQABAMgEQALgDAKgIIAIgGQALgJAGAAQAFAAADADQADADAAAFQAAAFgFAIQgGAIgJAGQgTAQgSAIQgRAGgVAAQguAAgfggg");
	this.shape_13.setTransform(11.4,-25.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AANAYIgahEQgNgfgKgFIgGgDQgNgFAAgIQAAgJALgDQALgEAiAAQAeAAALAEQAKADAAAJIgBAHIgEAEIgHADQgJAEAAAEIAEAPIARAtIATAqQAFAKADAAQADAAAEgGIAKgTIAXg3QAIgVAAgHIgCgIIgFgFIgGgDQgKgDAAgHQAAgJAKgDQAKgEAbAAQAXAAAJAEQAKADAAAIQAAAJgMAEIgHADQgLAFgTAtIgFALIgJAUQgyBxgOAAQgPAAgmhZgAiAAMIgGgNIgPglQgOglgJgFIgHgDQgNgFAAgIQAAgJAMgDQAKgEAkAAQAeAAAKAEQALADAAAJIgCAHIgEAEIgHADQgJAEAAAEIAFATIARApIASApQAGALACAAQAHAAAGgNIAHgQIAFgHQADgCAFAAQAFAAADADQADADAAAGQAAAFgGANQgWAygLARQgKAQgHAAQgQAAgrhlg");
	this.shape_14.setTransform(-17.8,-25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("Ag2CeQgYgGgPgJQgJgFgGgTQgFgSAAgZQAAgKADgFQAEgGAHAAQALAAAKAUIAGAJQAOAZAQAKQAQAMAXAAQAYAAAQgPQAQgNAAgWQAAgehAgcIgHgEQg1gVgRgUQgSgTAAgfQAAgoAdgZQAdgZAvAAIAZACIAeAHIAJgGIAHgCQAGAAAEADQAEAEAFAIQAHANAFAPQAEAOAAALQAAAIgEAEQgDADgGAAQgMAAgLgPIgDgFQgNgPgOgJQgOgHgTAAQgYAAgOAMQgOALAAATQAAASAMAMQAMAMAuAUIAJAEQAnARASAOQAMALAGAPQAGAPAAARQAAAtgfAZQgfAZg3AAQgbAAgYgFg");
	this.shape_15.setTransform(-48.8,-30.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.swetinspiration, new cjs.Rectangle(-109.9,-58.3,219.9,107.9), null);


(lib.seventeenvideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnwCvQhJAAgzg0Qg0gyAAhJQAAhHA0g0QAzgzBJAAIPhAAQBJAAAzAzQA0A0AABHQAABJg0AyQgzA0hJAAg");
	this.shape.setTransform(0,-10,1.097,1.097);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenvideo, new cjs.Rectangle(-73.7,-29.2,147.5,38.4), null);


(lib.seventeenrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnwCvQhJAAgzg0Qg0gyAAhJQAAhHA0g0QAzgzBJAAIPhAAQBJAAAzAzQA0A0AABHQAABJg0AyQgzA0hJAAg");
	this.shape.setTransform(0,-8,1.097,1.097);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrectangle, new cjs.Rectangle(-73.7,-27.2,147.5,38.4), null);


(lib.seventeenberries_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.seventeenberries();
	this.instance.parent = this;
	this.instance.setTransform(-43,-47.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenberries_1, new cjs.Rectangle(-43,-47.5,86,95), null);


(lib.partyreadyrecipes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgQByIgXgEIgHAEIgGABIgFgBIgEgDQgIgGgGgSQgGgSAAgQQAAgHAEgEQADgFAGAAQAKAAAKASIAJANQAGAIAMAFQALAFAMAAQAOAAAJgHQAIgHAAgMQAAgTgkgRIgMgGQgigRgMgOQgMgOAAgVQAAgcATgSQAUgSAgAAIAPABIAPACIAKgEIAHgBQALAAAKARQAKASAAASQAAAIgDAFQgEAEgGAAQgFAAgFgEQgFgEgGgLQgIgNgJgGQgJgFgMAAQgMAAgIAHQgHAHAAAMQAAAKAIAHQAHAIAbAOIACABQA9AdAAAjQAAAfgXAUQgYAVgjAAg");
	this.shape.setTransform(68.9,26.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhHBSQgfgfAAgwQAAgyAgghQAgghAxAAQAqAAAZAYQAZAYAAApQAAANgEAFQgEAEgRAAIhTAAQgHAAgEgEQgEgDAAgGQAAgGAEgDQAEgDAHAAIAtAAIALgBQADgCAAgFQAAgVgOgPQgPgOgTAAQgaAAgNAXQgMAWAAAgQAAAiARAZQARAYAbAAQAQAAAMgDQALgEAKgHIAIgGQALgJAGAAQAFAAADADQADAEAAAEQAAAFgFAIQgGAIgJAGQgTARgSAGQgRAHgVAAQguAAgfggg");
	this.shape_1.setTransform(48.1,26.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AhqCVQgLgEAAgJQAAgHAJgEIAMgFQAEgFACgRQACgRgBg3IAAgiQAAg8gBgRQgDgRgFgDIgKgEQgMgEAAgIQAAgFADgEQAEgDAJgEIAfgKQAOgDAIAAQAGAAADADQADADAAAIIAAALIAAAEIABABIAJgGIAIgGQANgKAMgFQANgFAMAAQApAAAaAeQAaAeAAAvQgBA0gdAiQgdAhgsAAQgTAAgHgFQgHgFAAgJQAAgFAEgDQADgEAHAAIAFABIAHABQAZAAAPgUQAOgUAAgiQAAglgQgWQgQgYgZAAQgWAAgNANQgNANAAAhIAACKIACAWQAAAJADADQADADAKACIAIADIAFAEIABAHQAAAIgMADQgNAEgfAAQgfAAgMgEg");
	this.shape_2.setTransform(23,30.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgmCcQgLgDAAgKQAAgHALgEIAGgDQAFgDADgHQACgHAAgRIAAgPIAAgRIAAgXQAAgigCgKQgCgKgEgDIgKgEQgOgEAAgHQAAgFAFgEQAEgEAIgDIAigLIAWgEQAGAAACAEQADAEAAAKIAAANIAAAKIgCA3IAAABIgBA2QAAAVACAIQACAJAFADIAIADQALAEAAAJQAAAIgLADQgKAEgdAAQggAAgLgEgAgahtQgKgIAAgLQAAgNALgJQAKgJAPAAQANAAAKAIQAJAIAAAMQAAAMgKAJQgKAIgPAAQgOAAgJgHg");
	this.shape_3.setTransform(4.4,21.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhEBSQgggfAAgwQAAgxAigiQAgghAwAAQAkAAAaATQAZASgBAaQAAAKgGAGQgIAHgKAAQgLAAgHgGQgHgFgIgRQgGgQgJgHQgIgFgOAAQgYAAgOASQgPATAAAiQAAAlAVAaQAUAYAeAAQAMAAAJgDQAKgDAIgGIAIgGQAMgKAHAAQAEAAADAEQADACAAAEQAAAGgFAIQgFAIgGAFQgSAQgSAHQgTAHgWAAQgtAAgeggg");
	this.shape_4.setTransform(-12.8,26.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhHBSQgfgfAAgwQAAgyAgghQAgghAxAAQAqAAAZAYQAZAYAAApQAAANgEAFQgEAEgRAAIhTAAQgHAAgEgEQgEgDAAgGQAAgGAEgDQAEgDAHAAIAtAAIALgBQADgCAAgFQAAgVgOgPQgPgOgTAAQgaAAgNAXQgMAWAAAgQAAAiARAZQARAYAbAAQAQAAAMgDQALgEAKgHIAIgGQALgJAGAAQAFAAADADQADAEAAAEQAAAFgFAIQgGAIgJAGQgTARgSAGQgRAHgVAAQguAAgfggg");
	this.shape_5.setTransform(-35.6,26.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AAvBtQgUhGgQgOQgPgOgWAAQgRAAAAgOQAAgNAOAAQAkAAARgOQASgOAAgeQAAgdgSgPQgSgOghAAQgRAAgGACQgHACgCAGIgCAUIgBAsIAABgIABBBQABAQAFADIAJAEQAOAFAAAJQAAAKgMAEQgMADgjAAQgiAAgMgDQgNgEAAgKQAAgJAOgFIAKgFQAEgDACgaQACgaAAhEIgBhTQgCgggDgEQgDgDgLgFQgMgEAAgJQAAgIAHgDQAHgEANAAIAwAAIAsgBIAjgBQAvAAAaAUQAZAVAAAmQAAAdgRAVQgRAVgeAJIAAACQAYAEANAPQANAOALAkIAGAWQAIAhANAAIAGAAIAIAAQAEAAAEADQADADAAAFQAAAKgNAHQgMAGgVAAQgrAAgPgzg");
	this.shape_6.setTransform(-62.3,21.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhlCRQgKgKAAgOQAAgLAIgHQAHgIALAAIAKABIAHAFIAGAJQAFAIAFAAQAKAAAMgQQAMgQgBgRQAAgTgPgjIgCgEIgjhNIgUgqQgEgIgMgGIgBAAQgIgCgCgEQgCgDgBgEQAAgKAMgEQAMgDAfAAQAggBALAEQAKADAAAJIgBAHIgDAEIgIADQgJAEAAAEIAEAQIASAsIARApQAGAKADAAQACABAGgLIAOgiIAPgsQAGgPAAgGQAAgGgMgHQgNgHAAgGQAAgHAKgDQAKgEAZABQAagBAJAEQAKADgBAJQAAAIgMAEIgJACQgMAHgOAmIgHAQIgcBGQgkBagWAcQgXAbggABQgQgBgLgIg");
	this.shape_7.setTransform(111.3,-20.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AhfCEQgagdAAgwQAAg1AdghQAeghAvAAIAPACQAHACAEAEQADAFAAAGQAAALgOAAIgGAAIgGAAQgYAAgPAUQgOATAAAiQAAAlAQAXQAPAXAZAAQAXAAAMgNQAMgNAAgYIAAg8IAAhkQAAgPgCgGQgDgGgIgDIgGgCQgOgDAAgIQABgGAFgEQAFgEAQgHIAZgGIAUgDQAIAAADAEQADAEABAKIgBALIgCCGIABBcQACAVADADIAPAFQAMACAAAIQAAAKggAKIgWAGIgRACQgGAAgCgDQgDgEAAgHIAAgLIgBgEIgBgBQgCABgFADIgJAHQgNAKgMAFQgMAFgOAAQgpAAgZgeg");
	this.shape_8.setTransform(88,-30.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAnBnIgMgMIgJAFQgbASgbAAQggAAgTgSQgUgTAAgeQAAgjAZgTQAagTAtAAQALAAAFADQAGADAAAJQAAAMgPAAQgVAAgOAKQgNALAAASQAAASAMAKQALALATAAQAVAAAJgKQAJgJAAgXIAAhTQAAgTgIgKQgJgLgOAAQgLAAgJAFQgJAFgJAKIgFAFQgNARgPAAQgIAAgFgFQgGgGAAgJQAAgVAagOQAZgOAoAAQAXAAASAGQARAHAKAMQAGAIADAOQADANAAAfIAABGQAAAMACAGQACAGAEACIAHACQAOADAAAIQAAAKgPAJQgOAIgUAAQgKAAgKgLg");
	this.shape_9.setTransform(62.8,-25.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AhHBSQgfgfAAgwQAAgyAgghQAgghAxAAQAqAAAZAYQAZAYAAApQAAANgEAFQgEAEgRAAIhTAAQgHAAgEgEQgEgDAAgGQAAgGAEgDQAEgDAHAAIAtAAIALgBQADgCAAgFQAAgVgOgOQgPgPgTAAQgaAAgNAXQgMAXAAAgQAAAhARAZQARAZAbgBQAQABAMgEQALgDAKgIIAIgGQALgJAGAAQAFAAADADQADADAAAFQAAAFgFAIQgGAIgJAGQgTAQgSAIQgRAGgVAAQguAAgfggg");
	this.shape_10.setTransform(39.4,-25.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AAvBtQgUhGgQgOQgPgOgWAAQgRAAAAgOQAAgNAOAAQAkAAARgOQASgOAAgeQAAgdgSgPQgSgOghAAQgRAAgGACQgHACgCAGIgCAUIgBAsIAABgIABBBQABAQAFADIAJAEQAOAFAAAJQAAAKgMAEQgMADgjAAQgiAAgMgDQgNgEAAgKQAAgJAOgFIAKgFQAEgDACgaQACgaAAhEIgBhTQgCgggDgEQgDgDgLgFQgMgEAAgJQAAgIAHgDQAHgEANAAIAwAAIAsgBIAjgBQAvAAAaAUQAZAVAAAmQAAAdgRAVQgRAVgeAJIAAACQAYAEANAPQANAOALAkIAGAWQAIAhANAAIAGAAIAIAAQAEAAAEADQADADAAAFQAAAKgNAHQgMAGgVAAQgrAAgPgzg");
	this.shape_11.setTransform(12.7,-30.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgqAXQgIAAgCgDQgDgCAAgGIACgKIAFgMQADgGADgCQADgCAJAAIALAAIATAAIAlgBIAGgBQAHAAADADQADACAAAGQAAAMgHAKQgHALgKAAIgKgBIgNAAIgwACIgDAAg");
	this.shape_12.setTransform(-10.9,-25.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AhlCRQgKgKAAgOQAAgLAIgHQAHgIALAAIAKABIAHAFIAGAJQAFAIAFAAQAKAAAMgQQAMgQgBgRQAAgTgPgjIgCgEIgjhNIgUgqQgEgIgMgGIgBAAQgIgCgCgEQgCgDgBgEQAAgKAMgEQAMgDAfAAQAggBALAEQAKADAAAJIgBAHIgDAEIgIADQgJAEAAAEIAEAQIASAsIARApQAGAKADAAQACABAFgLIAPgiIAPgsQAGgPAAgGQAAgGgMgHQgNgHAAgGQAAgHAKgDQAKgEAZABQAagBAJAEQAKADgBAJQAAAIgMAEIgJACQgMAHgOAmIgHAQIgcBGQgkBagWAcQgXAbggABQgQgBgLgIg");
	this.shape_13.setTransform(-29.1,-20.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgLCDQgLgDgIgHQgHgHgEgMQgDgMAAghIAAh0IgUAAIgGgCIgCgGIAAgFQAAgIAXgTIAJgHIAIgIQAXgUAIAAIAGACQADACAAADIAAApIAxAAQAFAAACACQACADAAAFIAAAGQAAAGgCACQgCACgFABIgtAAIgEABIgBAGIAABrQAAAcAFAIQAEAGANAAQAHABALgEIAPgDQAFAAADADQADACAAAFQAAAMgSALQgTALgYAAQgMAAgLgEg");
	this.shape_14.setTransform(-47.9,-27.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AhBBtQgLgEAAgKQAAgHAKgEIAGgCQAGgEACgHQACgHAAgRIAAgPIAAgRIAAgNQAAgogCgMQgCgMgEgDIgKgDQgNgEAAgIQAAgFAEgDQAEgEAJgEIAegKIATgEQALAAADAeIABAEIABABQALgSANgJQAMgJAMAAQAPAAAJAJQAJAKAAAPQAAAPgHAJQgGAJgNAAIgLgDIgJgGIgFgJQgCgFgDgBQgPABgGAUQgFAWAABBQAAATACAJQACALAGACIAJADQANAEAAAJQAAAIgMAEQgMADgeAAQghAAgKgDg");
	this.shape_15.setTransform(-63.6,-25.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AAnBnIgMgMIgJAFQgbASgbAAQggAAgTgSQgUgTAAgeQAAgjAZgTQAagTAtAAQALAAAFADQAGADAAAJQAAAMgPAAQgVAAgOAKQgNALAAASQAAASAMAKQALALATAAQAVAAAJgKQAJgJAAgXIAAhTQAAgTgIgKQgJgLgOAAQgLAAgJAFQgJAFgJAKIgFAFQgNARgPAAQgIAAgFgFQgGgGAAgJQAAgVAagOQAZgOAoAAQAXAAASAGQARAHAKAMQAGAIADAOQADANAAAfIAABGQAAAMACAGQACAGAEACIAHACQAOADAAAIQAAAKgPAJQgOAIgUAAQgKAAgKgLg");
	this.shape_16.setTransform(-83.8,-25.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AhxCbQgMgEAAgJQAAgJAOgFIAJgFQAFgEACgaQACgaAAhEIgChSQgCgggDgEQgCgDgMgFQgLgFAAgIQAAgIAHgEQAGgEAOAAIAXAAIAZAAIAsgBIAigBQAxAAAZAVQAYAVAAAqQAAAtgeAZQgeAXg6AAQgWAAAAgPQAAgPATAAQAbAAARgOQARgPAAggQAAgegRgOQgRgPgjAAQgQAAgHADQgGACgCAGIgDAUIgBAuIAABfIACA/QABAQAEADIAKAFQANAFAAAJQAAAJgMAEQgMAEgjAAQgiAAgMgEg");
	this.shape_17.setTransform(-108.3,-30.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyreadyrecipes, new cjs.Rectangle(-124.1,-58.3,248.2,107.9), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgRA7QgHgEgFgFQgFgGgDgHQgCgIAAgHQAAgJACgHQADgHAFgFQAFgGAHgDQAHgDAJAAQAIAAAHAFQAHAEAEAFIAAAAIAAg5IAPAAIAAB5IgOAAIAAgNIgBAAQgEAIgIADQgHADgHAAQgJAAgHgCgAgKgCQgEABgDADQgEAEgBAFQgCAFAAAGIACAKQABAEAEAFQADADAEACQAFADAFAAQAGAAAFgDQAFgCADgDQADgEACgFQACgFAAgFQAAgGgCgFQgCgFgDgEQgDgDgFgBQgFgDgGAAQgFAAgFADg");
	this.shape.setTransform(41.4,-6.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNAlQgHgDgFgFQgGgFgDgHQgDgIAAgJQAAgIADgHQADgIAFgEQAGgGAHgDQAHgDAHAAQAJAAAHADQAGADAFAFQAFAEACAIQADAHAAAJIAAACIAAADIg7AAQAAAEACAFQACAEADADQADADAFACQAEACAEgBQAIAAAGgCQAFgEADgFIALAJQgGAHgIAEIgJADIgKABQgHAAgIgDgAAXgGQAAgEgCgEIgEgHIgGgFQgEgBgGAAIgIABIgHAFQgDADgCAEQgCAEAAAEIAsAAIAAAAg");
	this.shape_1.setTransform(32,-4.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgVAnIAAg6IAAgIIAAgJIAOAAIAAAHIAAAGIABAAQADgHAFgEIAHgDIAHgBIAGABIgBANIgGAAQgGAAgEACIgGAFQgCAEgBAEIgCAJIAAAng");
	this.shape_2.setTransform(25.2,-4.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgHA5IAAhMIAPAAIAABMgAgGgnQgDgDAAgEQAAgEADgCQADgEADAAQAFAAACAEQADACAAAEQAAAEgDADQgCADgFAAQgDAAgDgDg");
	this.shape_3.setTransform(19.7,-6.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgnA6IAAhxIAOAAIAAAMIABAAQAEgGAHgEQAHgEAIAAQAJAAAHADQAHADAFAFQAFAGACAHQADAHAAAJQAAAIgDAHQgCAHgFAFQgFAGgHADQgHADgJAAQgHAAgHgEQgIgDgEgHIAAAAIAAAygAgKgqQgFACgDAEQgEADgBAFQgCAFAAAGQAAAFACAFQABAFAEADQADAEAFACQAFACAFAAQAGAAAEgCQAFgCADgEIAFgIIACgKQAAgGgCgFQgCgFgDgDQgDgEgFgCQgEgDgGAAQgFAAgFADg");
	this.shape_4.setTransform(12.8,-2.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQAlQgIgEgFgHIAKgJQADAFAGADQAFADAFAAIAGgBIAFgBIAEgEIABgFQAAgFgGgDQgEgDgJgBIgIgDIgHgDQgEgDgBgDQgDgEAAgFQAAgGADgEQACgFAEgDQAEgCAGgBQAFgCAFAAQAHAAAIADQAHAEAFAFIgLAJQgCgEgFgDQgFgCgFAAIgEAAIgFACIgDAEIgBAEQAAAEAEADQAFADAHABIAKADIAIADIAFAHQADAEAAAFQAAAGgDAFQgDAFgEADQgEADgFABIgMABQgIAAgIgDg");
	this.shape_5.setTransform(3.9,-4.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AATAnIAAgpIgBgJIgCgHQgCgEgEgCQgDgCgFAAQgIAAgGAIQgFAGgBAMIAAAnIgOAAIAAg6IAAgIIgBgJIAOAAIAAAHIAAAFIABAAIAEgFIAGgFIAHgDIAHgBQAHAAAFADQAGACADAEQAEAEACAGQABAGAAAGIAAAug");
	this.shape_6.setTransform(-4.2,-4.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHA5IAAhMIAPAAIAABMgAgGgnQgDgDAAgEQAAgEADgCQADgEADAAQAFAAACAEQADACAAAEQAAAEgDADQgCADgFAAQgDAAgDgDg");
	this.shape_7.setTransform(-10.9,-6.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgEAsQgFgHAAgLIAAgpIgPAAIAAgMIAPAAIAAgWIAOAAIAAAWIAUAAIAAAMIgUAAIAAAnQAAAHACADQADADAFAAIAFgBIAEgBIABAMIgGABIgHABQgLAAgFgFg");
	this.shape_8.setTransform(-19.7,-5.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgNAlQgHgDgFgFQgGgFgDgHQgDgIAAgJQAAgIADgHQADgIAFgEQAGgGAHgDQAHgDAHAAQAJAAAHADQAGADAFAFQAFAEACAIQADAHAAAJIAAACIAAADIg7AAQAAAEACAFQACAEADADQADADAFACQAEACAEgBQAIAAAGgCQAFgEADgFIALAJQgGAHgIAEIgJADIgKABQgHAAgIgDgAAXgGQAAgEgCgEIgEgHIgGgFQgEgBgGAAIgIABIgHAFQgDADgCAEQgCAEAAAEIAsAAIAAAAg");
	this.shape_9.setTransform(-26.8,-4.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgPA3QgLgEgIgJQgHgIgFgKQgEgLgBgNQABgNAEgKQAFgMAHgHIAJgHIALgGQALgDAMAAIAMAAIAMADQAKAFAIAGIgMAMQgFgGgHgDIgJgDIgJgBQgJAAgIAEQgIAEgGAGQgFAGgDAIQgDAJAAAIQAAAJADAIQADAJAFAGQAGAGAIADQAIAEAJAAQAJAAAGgCQAHgBAFgCIAAggIgaAAIAAgMIAqAAIAAA1QgJAFgLADQgOADgJgBQgNAAgLgEg");
	this.shape_10.setTransform(-37.8,-6.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-45.8,-18.3,94.7,23.7), null);


(lib.mainsidesforeight = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("Ag0A/IgFgBQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAhyQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAAAIAvAAIAMABIANAEQAMAEAKAIQAJAJAFALQADAGABAGQABAHAAAGQAAAOgFAMIgGALIgJAJIgKAHIgLAFQgMAFgNAAgAgigmQgCACAAADIAABFQAAAAAAABQABAAAAABQAAAAABAAQAAABABAAIAEACIAXAAQAIAAAIgDQAIgDAGgFQAGgFAEgIQADgHAAgKQAAgIgDgIQgEgHgGgGQgGgFgIgDQgIgDgIAAIgWAAQgDAAgDACg");
	this.shape.setTransform(110.4,-86.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgqA/IgEgCQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhzQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIAEgCIBXAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABIABADIAAAFIAAAEIgBAEIgDADIhBAAIgDACIgCAEIAAARQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIApAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAFIABAFIAAADQAAAFgFACIgoAAQgBAAAAAAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIAAATQAAABAAAAQAAABAAABQABAAAAAAQAAABABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIBAAAQAEACAAAFIAAAEIAAAFIgCAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(97.2,-86.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AACA/IgEAAIgFgBQgDgBgBgEIAAhcQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgGgCIgKAAIgKAAIgEAAQgEAAgCgDQgBgCAAgDIAAgEIABgFIABgDIAFgBIBWAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgZAAQgDAAgDACQgCABABAEIAABbQgBAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgEACg");
	this.shape_2.setTransform(85.3,-86.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAfA/IgCAAIgDgBIgBgBIgWgiIgDgEQgCgCgEAAIgQAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgBABAAAAQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAAAIAAAgQAAAAAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgEABIgFAAIgEAAQgEABgCgCQgCgBAAgFIAAhzQAAAAAAAAQAAgBABAAQAAgBAAAAQABgBAAAAIAEgBIA1AAQAJAAAIADQAJADAFAFQAHAGADAIQADAIAAAKQAAAKgEAHQgEAFgFAFIgJAHQgDACAAACIAAADIAEAHIAIAKIAHAKIACAHQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgEADIgFABIgEABgAgZgoQgDACAAADIAAAcQAAAEADACQACABADAAIAZAAQAGAAADgBQAFgBADgDQAEgCACgEQABgEAAgFQAAgLgHgFIgIgEIgJgBIgZAAIgFABg");
	this.shape_3.setTransform(74.1,-86.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAuA/IgHAAQgDgBgCgDIgHgRIgCgDQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgqAAIgCAAIgCABIgCACIgBABIgGARIgDACIgDABIgEABIgDAAIgEAAIgEAAIgDgCIgBgCIAzh2QAAgBAAAAQABgBAAAAQABAAAAAAQABgBAAAAIAEgBIAFABQAEAAABADIAxB1IAAABQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgEABIgFABgAgBgTIgBABIgBAEIgDAGIgDAHIgDAGIgCAGIgBACIABADIACABIAZAAIACgBIABgCIgCgGIgEgJIgEgLIgDgGIgDgBg");
	this.shape_4.setTransform(61,-86.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AACA/IgEAAIgFgBQgDgBgBgEIAAhcQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgGgCIgKAAIgKAAIgEAAQgEAAgCgDQgBgCAAgDIAAgEIABgFIABgDIAFgBIBWAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgZAAQgDAAgDACQgCABAAAEIAABbQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgEACg");
	this.shape_5.setTransform(49.7,-86.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgcA9QgNgGgKgKIgBgBIgBgDIACgEIADgEIAFgEIAEgBQADAAADACIAIAGIALAFQAGACAIABIAJgBQAFgBAFgCQAEgDADgDQADgEAAgFQAAgGgDgCQgEgDgFgCIgNgDIgOgBIgPgEQgHgCgGgCQgGgFgDgFQgEgHAAgJQAAgKAFgIQAFgHAIgEQAIgFAJgCQAJgCAHAAIANABIAMACIAMAFIAKAHIABADIAAACIgBAEIgEAEIgFADIgFABIgDgBQgHgGgHgDQgIgDgIAAIgIABQgFAAgEACQgEACgCAEQgDAEAAAFQAAAGAGAEQAGACAJABIASAEQALAAAJAEQAJAEAGAFQAGAIAAANQAAAKgFAIQgGAIgIAFQgIAFgJADQgKADgJgBQgNAAgOgEg");
	this.shape_6.setTransform(38.4,-86.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgEBCIgDgBIgCgCIgBgDIAAgsIgCgHIgDgGIgkg4IAAgBIABgEIAEgDIAFgDIAEAAIAEABIADACIAZApIADACIACABIADgBIACgCIAZgpIAEgDIAEgBIAEABIAFACIAEADQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAIAAACIAAABIgkA4IgEAHIAAADIgBACIAAAtQgCAFgEABIgGAAg");
	this.shape_7.setTransform(21.2,-86.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AACA/IgDAAIgHgBQgCgBAAgEIAAhcQAAgBgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgGgCIgKAAIgJAAIgGAAQgDAAgBgDQgCgCAAgDIAAgEIABgFIACgDIADgBIBXAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgaAAQgCAAgDACQgCABAAAEIAABbQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgDACg");
	this.shape_8.setTransform(10.3,-86.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAgA/IgDAAIgDgBIgBgBIgWgiIgDgEQgDgCgDAAIgPAAQgBAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAQAAAAgBABQAAABgBAAQAAABAAAAQAAABAAAAIAAAgQAAAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIgFABIgFAAIgEAAQgEABgCgCQgCgBAAgFIAAhzQAAAAAAAAQAAgBABAAQAAgBAAAAQABgBAAAAIAEgBIA1AAQAJAAAIADQAJADAFAFQAHAGADAIQADAIAAAKQAAAKgEAHQgEAFgFAFIgJAHQgEACAAACIABADIAFAHIAHAKIAGAKIADAHQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgEADIgFABIgEABgAgagoQgCACAAADIAAAcQAAAEACACQADABADAAIAaAAQAEAAAFgBQAEgBAEgDQADgCABgEQACgEAAgFQAAgLgGgFIgIgEIgJgBIgaAAIgGABg");
	this.shape_9.setTransform(-0.8,-86.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAuA/IgHAAQgDgBgCgDIgHgRIgCgDQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgqAAIgCAAIgCABIgCACIgBABIgGARIgDACIgDABIgEABIgDAAIgEAAIgEAAIgDgCIgBgCIAzh2QAAgBAAAAQABgBAAAAQABAAAAAAQABgBAAAAIAEgBIAFABQAEAAABADIAxB1IAAABQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgEABIgFABgAgBgTIgBABIgBAEIgDAGIgDAHIgDAGIgCAGIgBACIABADIACABIAZAAIACgBIABgCIgCgGIgEgJIgEgLIgDgGIgDgBg");
	this.shape_10.setTransform(-13.9,-86.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgsBAQgFAAgCgFIAAh2QAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBABAAIADgBIA2AAQAJAAAIADQAIACAGAGQAGAFAEAHQADAHAAAKIAAAGIgCAFQgFAMgIAFQgIAGgKACQgLACgKgBIgVAAIgCABIgCABIgBAFIAAAmIgDADIgEACIgFAAgAgbgnQAAABAAABQgBAAAAABQAAAAAAABQAAAAAAABIAAAVIABAEQABABAAAAQABAAAAABQABAAAAAAQABAAAAAAIAfAAIAIgBQADgBADgDQADgCACgDQACgDAAgEQAAgEgCgDQgCgDgDgCIgGgEQgDgBgDAAIggAAQgDAAgCACg");
	this.shape_11.setTransform(-25.6,-86.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgqA/IgEgCQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhzQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIAEgCIBXAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABIABADIAAAFIAAAEIgBAEIgDADIhBAAIgDACIgCAEIAAARQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAABAAIApAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAFIABAFIAAADQAAAFgFACIgoAAQgBAAAAAAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIAAATQAAABAAAAQAAABAAABQABAAAAAAQAAABABAAQAAABABAAQAAAAAAAAQABABABAAQAAAAABAAIBAAAQAEACAAAFIAAAEIAAAFIgCAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_12.setTransform(-43.5,-86.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgsBAIgEgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAIAAh4IADgCIAEgCIAFAAIAEAAQAFAAACAFIAAAoQAAABAAAAQAAABABABQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAQAAABABAAQAAAAABAAIArAAQADAAACgCQACgCAAgDIAAgoQADgEADAAIAIgBIAGABIAEAEIgBB3QgBAEgEAAIgHAAIgGAAIgFgEIAAgsQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAgBgBQgCgCgCAAIgqAAQgDAAgDADQgCACAAADIAAArQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgEABIgFABg");
	this.shape_13.setTransform(-56.9,-86.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AACA/IgEAAIgFgBQgDgBgBgEIAAhcQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgGgCIgKAAIgKAAIgEAAQgEAAgCgDQgBgCAAgDIAAgEIABgFIABgDIAFgBIBWAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgZAAQgDAAgDACQgCABAAAEIAABbQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgEACg");
	this.shape_14.setTransform(-69.1,-86.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AACA/IgEAAIgFgBQgDgBgBgEIAAhcQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgGgCIgKAAIgKAAIgEAAQgEAAgCgDQgBgCAAgDIAAgEIABgFIABgDIAFgBIBWAAQADAAABACIACAGIgBAEIAAAEIgCAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgZAAQgDAAgDACQgCABAAAEIAABbQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgEACg");
	this.shape_15.setTransform(-84.8,-86.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgqA/IgEgCQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhzQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAEgCIBXAAQAAAAABABQAAAAAAAAQABAAAAABQABAAAAABIABADIAAAFIAAAEIgBAEIgDADIhBAAIgDACIgCAEIAAARQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIApAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAFIABAFIAAADQAAAFgFACIgoAAQgBAAAAAAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIAAATQAAABAAAAQAAABAAABQABAAAAAAQAAABABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIBAAAQAEACAAAFIAAAEIAAAFIgCAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_16.setTransform(-95.5,-86.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgKBAQgGgBgGgCQgGgDgFgEIgLgIQgFgDgDgGIgGgLQgGgNAAgNIABgNIAFgNQAFgLAJgJIALgIIALgGIAMgDIANgBIAOABQAIABAGADQAOAGAJALIAAACIgBAFIgEAEIgFAEIgEABQgDAAgDgCIgGgGQgEgEgHgCQgFgCgJgBQgIABgIADQgHAEgHAFQgFAGgEAIQgDAIAAAIQAAAJADAIQAEAHAFAGQAHAHAHADQAIADAIABIAJgBIAJgDIAHgEIAGgHIAAgCQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBgBAAIgDgCIgXAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAIgBgEIgBgFIAAgDIABgFQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAIA2AAIABABIACABQACAGABAGIAAAFIgCAGQgDAJgHAIQgGAGgHAGQgJAFgJADQgJACgKAAQgGABgHgCg");
	this.shape_17.setTransform(-109.9,-86.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.mainsidesforeight, new cjs.Rectangle(-119.1,-97.2,238.3,22.4), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgMAAgTQAAgRANgNQAMgNASAAQASAAANANQANANAAARQAAATgNAMQgNANgSAAQgSAAgMgNgAgYgYQgJAKgBAOQABAQAJAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAQQAAAMgMACIAPAVgAgHgDIAHAAQAMAAAAgHQAAgIgMAAIgHAAg");
	this.shape.setTransform(35,15.9,0.269,0.269);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgHgEQgJgFAAgNQAAgKAGgGQAFgHAJAAIARAAQAKAAAFgMQACgKAAgXIAAl5QAAgXgCgKQgFgLgKAAIgRAAQgJAAgFgHQgGgHAAgKQAAgNAJgFQAHgEAVgDQBcgNBsAAQBOAAA1ASQA1ASAnAoQAlAlAVA5QATA4AABEQAABNgZA9QgZA+gwAlQgkAegxAOQgwAOhFAAQh4AAhQgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBNAEArhAQArg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(16.7,8.1,0.269,0.269);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgCAAgIIAAiTQAAgKgLAAIgzAAQgKAAAAgOQAAgWAKAAICfAAQAMAAAAASQAAASgLAAIgyAAQgLAAAAAKIAACTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(21.8,23.7,0.269,0.269);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAASgMAAIh5AAQgIAAAAAJIAAAcQAAAKAKgBIBFAAQALABAAARQAAARgKAAIhFAAQgLAAAAAKIAAAfQAAAKAKAAIB3AAQALAAAAATQAAARgKAAg");
	this.shape_3.setTransform(14,23.7,0.269,0.269);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA5BlQgEgBgEgFIhAhGQgKgIgUAAQgFAAgEAEQgEAFAAAGIAAA7QAAAIgGACQgEACgKAAQgRAAAAgMIAAi0QAAgIAFgDQAEgCALAAQARAAAAAMIAAA3QAAANAKAAQALAAAFgCQAEgBAFgFIBJhDQAMgLANALQALAMgJAJIhAA7QgJAHAIAKIBPBVQAIAJgGAFQgFAEgNAAQgMAAgGgCg");
	this.shape_4.setTransform(6.1,23.7,0.269,0.269);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgggxQgFgKgKAAIgtAAQgEAAgDADQgDAEgBAEIABAxQAAAGgKABIgPABQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFAEQgEAEgPAAQgRAAgGgJgAg5g4IAAAuQABAFAEAEQAEABAFAAIA+AAQAQAAALgHQALgJAAgRQAAgQgLgIQgLgJgQAAIg+AAQgOAAAAAKg");
	this.shape_5.setTransform(-3,23.7,0.269,0.269);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBfIgOgbQgDgGgGAAIhTAAQgJAAgEAMIgMAVQgDAIgSAAQgXAAAGgMIBZi4QAFgKAKABQAMAAADAIIBYC6QADAHgJADQgGABgIAAQgPABgDgJgAgEgdIgYAyQgCADABACQACADAEAAIAwAAQADAAACgCQACgCgCgDIgZgzQgCgEgDABQgCAAgCADg");
	this.shape_6.setTransform(-11.9,23.7,0.269,0.269);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgPhsQgBgGgFAAQgDAAgDAEIgxA9QgEAGgFAAQgHAAgEgGIgtg8QgCgDgEAAQgFAAgBAIIgOBnQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgKADgDQAEgEALAAQAJAAAGAJIA4BOQAFAIAEAAQAFAAAGgIIA7hQQAFgIAKAAQAGAAADADQAEACACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-21,23.7,0.269,0.269);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAfhCA7gnQAZgTAmgTQAngTAmgOQAKgDgDgJQgCgKgOADQg5ALgsgRQgXgJgdgSQgggUgKgEQgtgWg7AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgQQgfgPgegbQgggdgugCQgsgCgbAVQgLAJADAGQADAHALgCQBPgRAxA3QAkAoAuAPQA4ASAugeIAZgXQANgMAMADQAPAEgBAUQgBAUgTAZQgiAsg+AeQhEAjgfAeQgwAvgTA9QgPAzAABRQAABxAqBAQAqBABKAAQBJAAArhCQArhBAAhwQAAhfgYg4QgZg6g1gUQgbgLAFgTQAFgUAhgDQA3gHA8AtQBoBMAACkQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(3.9,-14.6,0.269,0.269);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgLgHgBQgGAAgCALIgBACQgYBfhHA2QhGA2hpAAQh+AAhMhQQhLhQgBiFQAAiHBMhRQBLhQCAAAQBpAABIA3QBGA2AXBgQACALAGAAQAHgBACgLIABAAQAXhgBGg1QBHg3BoAAQB/AABMBQQBNBPAACFQAACHhNBRQhMBRiBAAQhmAAhHg3gACmiqQgoA/AABuQAABsAoA+QApA9BIAAQBFAAApg/QApg/ABhrQAAhsgqg+QgqhAhGAAQhGAAgpA/gAmFiqQgpA/AABuQAABrApA/QApA9BHAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhGAAQhGAAgpA/g");
	this.shape_9.setTransform(-5.6,8.1,0.269,0.269);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgKAAgXIAAl7QAAgZgDgIQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQANAAAHAFQAIAFACALIAMA7QAEAQgGAJQgFAJgLAAQgPAAgHgOIgJgSQgFgPgPgFQgNgEggAAIhtAAQghAAgJAIQgIAJAAAiIAABlQAAAZAIAFQAFAEAdAAIBFAAQAbAAAIgEQAHgDACgNIAAgFQAEgVATAAQAOAAAFAIQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgWIgBgGQgCgNgHgDQgHgEgbAAIhFAAQgdAAgFAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-26.4,8.1,0.269,0.269);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEcIgSgFQgKAAgIAIQgLAIgKAAQgKABgGgHQgFgGgEgQIgWhUQgCgIAAgJQAAgMAIgHQAHgIAMAAQAMAAAJALIAMARQAWAfAiASQAhASAlAAQAoAAAZgVQAbgVAAgiQAAgggcgfQgYgbhBguIhOg2QgRgPgUgWQggglAAg0QAAg9ArgmQArglBGAAQAmgBAjAIIAVAFQAHACAFAAQAHAAAMgIQAJgHAJABQATAAAFAXIAUBcQABAEABAIQAAAIgIAGQgHAGgKAAQgMAAgKgPQgOgVgHgHQgGgHgOgLQgigbguAAQgcAAgSAQQgRAQAAAaQAAAWAJANQANASAaAVIApAdQAzAkAWARQAXASAUAUQAWAWAMAeQAMAfAAAgQAABKgyAtQgzAshUAAQgyAAgmgLg");
	this.shape_11.setTransform(29.5,8.1,0.269,0.269);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah9EYQgLgKgIgWIhIjYQgBgGgEAAQgFAAgBAFIhODZIgJAVQgDAHgFAEQgMAKgRgBQgSABgLgKQgKgIgJgYIinm+QgJgagHgIQgIgHgUgEQgNgCgFgGQgGgFABgLQAAgVAcAAICvAAQAdAAAAAWQgBAMgGAEQgIAGgQABQgPABgFAFQgHAFAAAKQAAAIAEALIBzFGQACAGAEgBQAEAAADgGIA/i2QAHgagGgVIgfhbIgHgUQgEgJgGgFQgGgEgQgEQgNgDgFgFQgGgFABgJQAAgaAdAAICmAAQAdAAABAWQAAAUgcAEQgRACgGAEQgGAFAAAMQAAAIAJAbIBfEsQACAGAEgBQAEgBACgEIBdk6QADgNAAgHQAAgTgcgEQgbgCAAgVQgBgNAIgGQAIgFAQAAIEmAAQAVAAAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgGALQgBAIAAAZIAABuQAAAdAFAGQAFAHAYAAIB0AAQAXAAAHgIQADgDAAgHIAAgdIAAhpQAAgbgCgGQgFgLgLAAIgPAAQgKAAgHgGQgGgIgBgKQABgOAIgFQAJgFAVAAICaAAQAXAAAIAFQAJAFAAAOQgBAKgGAIQgHAGgJAAIgRAAQgEAAgEAEQgFADgBAEQgDAHAAAaIAAF9QAAAZADAIQAEAKAKAAIARAAQAKABAGAGQAHAIAAAJQgBAPgHAEQgJAGgXAAIiaAAQgVAAgJgGQgIgEAAgPQABgJAGgIQAHgGAJgBIAPAAQALAAAFgKQACgGAAgbIAAh8IAAgeQAAgGgDgFQgHgHgXAAIh0AAQgYAAgFAGQgFAIAAAcIAACCQAAAYABAJQAGAKALAAIAQAAQAJABAGAGQAFAIAAAKQABANgJAGQgHAFgVAAIibAAQgVAAgJgGQgJgFAAgOQAAgJAHgIQAGgGAKgBIAQAAQAFAAAEgCQAFgDAAgFQAEgGAAgbIAAl9QAAgxgkAFQgMACgGAIQgIAJgHAXIiGGyQgKAfgKAMQgKALgTgBQgTAAgLgJg");
	this.shape_12.setTransform(-20.1,-9.9,0.269,0.269);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgVAAgIgFQgJgFAAgOQAAgKAHgGQAGgHAJAAIAQAAQAEAAAEgDQAFgDABgFQADgHAAgZIAAl+QAAgZgDgJQgDgLgLABIgQAAQgKgBgHgGQgHgHAAgKQAAgOAJgGQAJgFAWAAICdAAQAWAAAJAFQAJAGAAAOQAAAKgHAHQgHAGgJABIgRAAQgOgBgEALQgDAHAAAbIAAFjQAAAcADAKQACAJAHAFQAHAEAKACQAMABAaAAIAwAAQAvAAAPgfIAHgPQAIgQAPgBQAMABAFAIQAFAJgDAQIgNBCQgFAVgaAAg");
	this.shape_13.setTransform(18.6,-10,0.269,0.269);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgJgGAAgOQAAgJAHgHQAGgGAJAAIARAAQAEAAAEgDQAEgEABgEQAEgKAAgYIAAl7QAAgXgEgKQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAJgMAAQgOAAgIgOQgDgFgFgNQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAHAFQAFADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgWIgBgGQgCgNgHgDQgHgEgbAAIgmAAQgeAAgFAEQgHAFAAAZIAABsQAAAiADALQADALAKAEQAQAGAhAAIBVgBQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgFAVgaAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(30.7,-10,0.269,0.269);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZMQk6iFjyjyQjyjxiFk7QiKlFAAlkQAAljCKlFQCFk6DyjzQDyjxE6iFQFFiKFjAAQFkAAFFCKQE6CFDyDxQDyDyCFE7QCKFFAAFjQAAFkiKFFQiFE7jyDxQjyDyk6CFQlFCKlkAAQljAAlFiKg");
	this.shape_15.setTransform(0,0,0.269,0.269);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalelogo, new cjs.Rectangle(-47,-47,94,94), null);


(lib.holidayhosting = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgQByIgXgEIgHAEIgGABIgFgBIgEgDQgIgGgGgSQgGgSAAgQQAAgHAEgEQADgFAGAAQAKAAAKASIAJANQAGAIAMAFQALAFAMAAQAOAAAJgHQAIgHAAgMQAAgTgkgRIgMgGQgigRgMgOQgMgOAAgVQAAgcATgSQAUgSAgAAIAPABIAPACIAKgEIAHgBQALAAAKARQAKASAAASQAAAIgDAFQgEAEgGAAQgFAAgFgEQgFgEgGgLQgIgNgJgGQgJgFgMAAQgMAAgIAHQgHAHAAAMQAAAKAIAHQAHAIAbAOIACABQA9AdAAAjQAAAfgXAUQgYAVgjAAg");
	this.shape.setTransform(116,26.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhqCVQgLgEAAgJQAAgHAKgEIALgFQAEgFACgRQABgRABg3IAAgiQgBg8gBgRQgDgRgEgDIgKgEQgOgEAAgIQAAgFAEgEQAEgDAJgEIAfgKQAOgDAIAAQAGAAADADQACADAAAIIAAALIABAEIABABIAJgGIAIgGQANgKAMgFQANgFAMAAQApAAAaAeQAZAeAAAvQAAA0gdAiQgdAhgsAAQgTAAgHgFQgHgFAAgJQAAgFAEgDQADgEAHAAIAFABIAHABQAZAAAPgUQAOgUAAgiQAAglgQgWQgQgYgZAAQgWAAgNANQgNANAAAhIAACKIACAWQAAAJADADQADADAJACIAJADIAFAEIABAHQAAAIgMADQgNAEgfAAQgfAAgMgEg");
	this.shape_1.setTransform(93.1,30.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgmCcQgLgDAAgKQAAgHALgEIAGgDQAFgDACgHQADgHAAgRIAAgPIAAgRIAAgXQAAgigDgKQgBgKgEgDIgKgEQgOgEAAgHQAAgFAFgEQADgEAJgDIAigLIAWgEQAGAAACAEQADAEAAAKIAAANIAAAKIgCA3IAAABIgBA2QAAAVACAIQACAJAFADIAIADQALAEAAAJQAAAIgLADQgLAEgcAAQggAAgLgEgAgahtQgKgIAAgLQAAgNALgJQAKgJAPAAQANAAAKAIQAJAIAAAMQAAAMgKAJQgLAIgOAAQgOAAgJgHg");
	this.shape_2.setTransform(74.5,21.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgtCcQgNgEAAgKQAAgJAMgEQAMgFACgDQADgEABgkIABhmIAAg6IgCgjQgBgGgEgCQgEgCgIAAIgKAAQgPAAgIAEQgJADgGAJIgHAPIgGAOIgGAHQgEADgEAAQgHAAgDgGQgDgGAAgNQAAgdAHgSQAHgRAKAAIADAAQARADAaAAICAAAQAbAAARgDIADAAQAKAAAHARQAHASAAAdQAAANgDAGQgDAGgHAAIgIgDIgGgHIgGgOIgHgPQgGgJgJgDQgIgEgQAAIgJAAQgIAAgEACQgEACgBAGIgBAjIgBA6IABBmQABAkADAEQACADAMAFQAMAEAAAJQAAAKgNAEQgMADgiAAQghAAgMgDg");
	this.shape_3.setTransform(54.2,21.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhQCPQgcgRAAgYQAAgLAGgHQAFgIANAAQAJAAAFAGQAFAFADAKQAFAQAOAJQAOAKAaAAQAdAAATgMQATgLAAgRQAAgKgHgGQgHgGgOAAIgZACIghACQgnAAgVgNQgVgNAAgSQAAgLAIgKQAHgKAQgKQgNgLgGgOQgHgOAAgRQAAgjAbgYQAbgYApAAIAWACIAiAHQAIAAAKgEQAJgEAOgKIAHAHIACAIQAAAJgHAIQgHAJgMAHIAGARIADASQAAAlgbAWQgbAWgqAAIgXgCIgUgEIgHAIIgCAIQAAALAKAFQAKAFAWAAIAggDIAjgCQAeAAAQAMQAQANAAAXQAAAigiAYQgiAXg0AAQgqAAgbgRgAgjhsQgMAOAAAWQAAAWALAOQAMAOARAAQASAAAMgOQAMgOAAgWQAAgWgLgOQgMgOgSAAQgRAAgMAOg");
	this.shape_4.setTransform(17.3,30.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhrBtQgLgEAAgKQAAgHALgEIAGgCQAFgDADgIQACgHAAgRIAAgPIAAgRIAAgWQAAgigCgLQgCgKgEgCIgKgFQgOgDAAgIQAAgFAFgDQAEgEAJgEIAfgKIAXgEQAGAAADAEQADACAAAIIAAAPIAAACIABAAIACAAIAAgBIAGgFIAEgDQAYgXAbAAQAPAAAPAHQAPAGAKAMQAKANAEAQQAEAQAAAkIAAAcIAAAPIAAAMQAAAQACAGQACAHAGADIAFACQALAEAAAHQAAAKgKAEQgKACgiAAQgfAAgKgCQgKgEAAgIQAAgIALgFIAIgDQAFgDACgKQACgJAAgXQAAhFgJgSQgJgSgXAAQgLAAgKAIQgLAHgGALQgEAKgCARQgCAQAAArQAAAVACAIQABAGAFADIAIADQALAFAAAIQAAAIgKAEQgLADgdAAQghAAgLgDg");
	this.shape_5.setTransform(-8.2,26.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgmCcQgLgDAAgKQAAgHALgEIAGgDQAFgDADgHQACgHAAgRIAAgPIAAgRIAAgXQAAgigCgKQgCgKgFgDIgJgEQgOgEAAgHQAAgFAFgEQAEgEAIgDIAhgLIAXgEQAGAAADAEQACAEAAAKIAAANIAAAKIgCA3IAAABIgBA2QAAAVACAIQACAJAFADIAIADQALAEAAAJQAAAIgLADQgKAEgdAAQggAAgLgEgAgahtQgKgIAAgLQAAgNALgJQAKgJAPAAQANAAAJAIQAKAIAAAMQAAAMgKAJQgLAIgOAAQgOAAgJgHg");
	this.shape_6.setTransform(-27.4,21.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgLCDQgLgDgIgHQgHgIgEgMQgDgMAAggIAAh1IgUAAIgGgBIgCgGIAAgFQAAgHAXgUIAJgHIAIgIQAXgUAIAAIAGACQADACAAADIAAApIAxAAQAFAAACACQACACAAAGIAAAGQAAAFgCADQgCACgFAAIgtAAIgEACIgBAGIAABrQAAAcAFAIQAEAGANABQAHAAALgEIAPgDQAFAAADACQADADAAAFQAAAMgSALQgTALgYAAQgMAAgLgEg");
	this.shape_7.setTransform(-41.2,24.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgQByIgXgEIgHAEIgGABIgFgBIgEgDQgIgGgGgSQgGgSAAgQQAAgHAEgEQADgFAGAAQAKAAAKASIAJANQAGAIAMAFQALAFAMAAQAOAAAJgHQAIgHAAgMQAAgTgkgRIgMgGQgigRgMgOQgMgOAAgVQAAgcATgSQAUgSAgAAIAPABIAPACIAKgEIAHgBQALAAAKARQAKASAAASQAAAIgDAFQgEAEgGAAQgFAAgFgEQgFgEgGgLQgIgNgJgGQgJgFgMAAQgMAAgIAHQgHAHAAAMQAAAKAIAHQAHAIAbAOIACABQA9AdAAAjQAAAfgXAUQgYAVgjAAg");
	this.shape_8.setTransform(-58.6,26.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AhPBSQgfggAAgxQAAgxAhggQAgghAxAAQAuAAAfAfQAeAeAAAxQAAAxghAiQggAigvAAQgvAAgfgggAgphAQgOARAAAdQAAArATAdQASAdAaAAQAVABANgTQAOgSAAgdQAAgqgSgdQgUgegYABQgWgBgNATg");
	this.shape_9.setTransform(-80.2,26.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAwCaQgLgEAAgJQAAgJANgFIALgFQADgDABgOIACgzIgBgfIgCgIQgCgEgKgCQgLgCgpAAIguACQgMABgDADIgDAGIgBARIAAASIACAzQABAOADADIAKAFQAOAFAAAJQgBAJgMAEQgLAEgkAAQghAAgNgEQgMgEAAgJQAAgJAOgFIAJgFQAFgEACgbQACgcAAhBIgChRQgCghgCgEQgDgDgLgFQgMgFAAgJQAAgIAKgDQAKgEAnAAQAnAAAKAEQAJADABAIQAAAJgOAFIgKAFQgEADgBAOIgCBAQABAJAHADQAJADAgAAIARAAIAugBQAOgBAEgEIACgEIABgIIAAgKIgCg2QgBgLgDgDIgLgFQgNgFAAgJQAAgIAKgDQALgEAlAAQAoAAAKADQAJAEAAAIQAAAJgOAFIgJAFQgEAEgCAdQgDAeAAA6IACBUQACAhACAFQADADAMAEQALAFAAAJQAAAJgMAEQgMAEgjAAQgiAAgNgEg");
	this.shape_10.setTransform(-109,21.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AhlCRQgKgKAAgOQAAgLAIgHQAIgIALAAIAJABIAHAFIAFAJQAHAIADAAQALAAAMgQQALgQAAgRQAAgTgPgjIgCgEIgjhNIgUgqQgEgIgNgGIAAAAQgIgCgCgEQgDgDABgEQAAgKALgEQALgDAhAAQAfgBALAEQALADAAAJIgBAHIgFAEIgIADQgIAEAAAEIAFAQIARAsIASApQAFAKADAAQACABAGgLIANgiIAQgsQAGgPAAgGQAAgGgNgHQgMgHAAgGQAAgHAKgDQAKgEAZABQAagBAKAEQAIADABAJQAAAIgNAEIgJACQgMAHgOAmIgGAQIgcBGQgkBagXAcQgXAbggABQgQgBgLgIg");
	this.shape_11.setTransform(66,-20.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AAnBnIgMgMIgJAFQgbASgbAAQggAAgTgSQgUgTAAgeQAAgjAZgTQAagTAtAAQALAAAFADQAGADAAAJQAAAMgPAAQgVAAgOAKQgNALAAASQAAASAMAKQALALATAAQAVAAAJgKQAJgJAAgXIAAhTQAAgTgIgKQgJgLgOAAQgLAAgJAFQgJAFgJAKIgFAFQgNARgPAAQgIAAgFgFQgGgGAAgJQAAgVAagOQAZgOAoAAQAXAAASAGQARAHAKAMQAGAIADAOQADANAAAfIAABGQAAAMACAGQACAGAEACIAHACQAOADAAAIQAAAKgPAJQgOAIgUAAQgKAAgKgLg");
	this.shape_12.setTransform(43.5,-25.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AhfCEQgagdAAgwQAAg1AeghQAdghAvAAIAPACQAHACADAEQAEAFAAAGQAAALgOAAIgGAAIgGAAQgYAAgPAUQgOATAAAiQAAAlAQAXQAQAXAYAAQAWAAANgNQAMgNAAgYIAAg8IAAhkQABgPgDgGQgDgGgIgDIgGgCQgNgDAAgIQAAgGAEgEQAGgEARgHIAYgGIAVgDQAHAAADAEQADAEAAAKIAAALIgCCGIABBcQACAVADADIAPAFQAMACAAAIQAAAKggAKIgVAGIgRACQgHAAgCgDQgDgEAAgHIAAgLIgBgEIgBgBQgCABgFADIgJAHQgNAKgLAFQgNAFgNAAQgpAAgageg");
	this.shape_13.setTransform(19.3,-30.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgmCcQgLgDAAgKQAAgHALgEIAFgDQAGgDACgHQADgHAAgRIAAgPIAAgRIAAgXQgBgigCgKQgBgKgEgDIgKgEQgOgEAAgHQAAgFAFgEQADgEAJgDIAigLIAWgEQAGAAACAEQADAEAAAKIAAANIgBAKIgBA3IAAABIgBA2QAAAVACAIQACAJAFADIAIADQALAEAAAJQAAAIgLADQgLAEgcAAQggAAgLgEgAgahtQgKgIAAgLQAAgNALgJQAKgJAPAAQANAAAKAIQAJAIAAAMQAAAMgKAJQgLAIgOAAQgOAAgJgHg");
	this.shape_14.setTransform(-0.7,-30.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgkCdQgLgEAAgJQAAgHAJgEIALgGQAEgEABgNIACgrIgBgiIAAgpIAAgQQAAg4gCgQQgBgPgFgDIgNgFQgOgEAAgHQAAgGAEgEQAEgDAQgGIAdgIIAWgCQAHAAADADQACAFAAAKIgBARQgCBOAABOIABBLQACAPAEAFIAMAGQAKAEAAAJQAAAHgLAEQgLAEgdAAQggAAgKgEg");
	this.shape_15.setTransform(-13.3,-30.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AhPBSQgfggAAgxQAAgwAgghQAighAwAAQAuAAAfAfQAeAfAAAvQAAAyggAiQghAigvAAQgvAAgfgggAgphAQgOARAAAeQAAAqATAeQATAcAZAAQAVAAAOgSQANgRAAgeQAAgqgTgdQgSgdgaAAQgVgBgNATg");
	this.shape_16.setTransform(-31.3,-25.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AAwCaQgLgEAAgJQAAgJANgFIAKgFQAEgDACgOIABgzIgBgfIgBgIQgDgEgLgCQgKgCgpAAIguACQgMABgDADIgEAGIAAARIAAASIABAzQACAOADADIAKAFQAOAFAAAJQAAAJgNAEQgLAEgkAAQgiAAgLgEQgNgEAAgJQAAgJAOgFIAJgFQAFgEACgbQACgcAAhBIgChRQgBghgEgEQgCgDgLgFQgMgFAAgJQAAgIAKgDQAKgEAnAAQAmAAAKAEQALADAAAIQAAAJgOAFIgKAFQgDADgCAOIgCBAQABAJAHADQAJADAgAAIARAAIAugBQANgBAFgEIACgEIABgIIAAgKIgBg2QgCgLgEgDIgKgFQgNgFAAgJQAAgIAKgDQAKgEAmAAQAoAAAKADQAJAEAAAIQAAAJgOAFIgJAFQgEAEgDAdQgCAeAAA6IACBUQACAhADAFQACADALAEQAMAFAAAJQAAAJgMAEQgMAEgjAAQgiAAgNgEg");
	this.shape_17.setTransform(-60.2,-30.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidayhosting, new cjs.Rectangle(-127.6,-58.3,255.3,107.9), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgYcgkyMAw5AAAMAAABJlMgw5AAAg");
	this.shape.setTransform(0,0,1.019,1.017);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-160.5,-240.5,321,481), null);


(lib.fourteentopright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteencookietopright();
	this.instance.parent = this;
	this.instance.setTransform(-49.5,-63.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentopright, new cjs.Rectangle(-49.5,-63.5,99,127), null);


(lib.fourteentopleft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteencookietopleft();
	this.instance.parent = this;
	this.instance.setTransform(-95,-69.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentopleft, new cjs.Rectangle(-95,-69.5,190,139), null);


(lib.fourteentable = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.seventeentable();
	this.instance.parent = this;
	this.instance.setTransform(-160,-240);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentable, new cjs.Rectangle(-160,-240,320,480), null);


(lib.fourteenbottomright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteenpiebottomleft();
	this.instance.parent = this;
	this.instance.setTransform(-113.5,-103);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteenbottomright, new cjs.Rectangle(-113.5,-103,227,206), null);


(lib.fourteenbottomleft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteencookiebottomleft();
	this.instance.parent = this;
	this.instance.setTransform(-47.5,-85.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteenbottomleft, new cjs.Rectangle(-47.5,-85.5,95,171), null);


(lib.classicturkeydinner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape.setTransform(132.2,84.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("Ag6BgQgKgEAAgIQAAgHAKgDIAFgCQAFgDACgGQACgHABgOIgBgOIAAgPIAAgMQAAgigBgLQgCgKgFgDIgIgEQgLgDAAgGQgBgFAEgEQADgDAJgDIAagJIARgDQAJAAAEAaIAAAEIABABQAJgQALgIQAMgIALAAQANAAAIAIQAIAIAAANQAAAOgHAIQgFAIgMgBIgKgCIgIgFIgDgHQgDgGgCAAQgNAAgGATQgEASAAA6QAAARABAJQADAIAFACIAIADQALAEAAAHQAAAHgKAEQgMADgZAAQgeAAgJgDg");
	this.shape_1.setTransform(115.1,84.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AhGBIQgbgcAAgrQAAgrAdgdQAdgdAqAAQAqAAAbAbQAaAbAAArQAAAsgcAeQgdAegpAAQgqAAgcgdgAgkg5QgMAQAAAaQAAAlAQAaQARAaAWAAQATAAAMgQQAMgQAAgbQAAgkgQgaQgRgagXAAQgSAAgMAQg");
	this.shape_2.setTransform(96.4,84.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("ABICIQgKgEAAgIQgBgHAMgGIAJgDQADgDACgIQABgJAAgaIAAgKIAAhSIgBgxIgYBAQg5CUgMAAQgGAAgMgVQgKgTgchAIgqhgIgCBMIAAA0IABAkQABAIADADIAJADQAMAFAAAIQAAAIgKAEQgKADgYAAQgVAAgJgEQgKgDAAgIQAAgHALgFQAKgFABgEQADgJADgyQACgwAAg9IAAgGQABgVgCgHQgCgHgEgCIgJgFQgNgEAAgIQAAgIAJgCQAJgDAcgBIAcABIAHACQAEADAOAiIAKAcIAGANQAuB0AEgBQAEAAASgpQARgpAXhEIAFgMQAHgVAFgHQAEgDAHgBIAagCQAaABAJADQAJACAAAIQAAAIgLAEIgGACQgGAEgCAHQgCAIAAAdIACBuQACAxADAHQAAAFAKADIADABIAIAGQACACAAAEQAAAIgLAEQgKADghAAQgdAAgKgDg");
	this.shape_3.setTransform(68,80.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("Ah0B1QgkgbAAguQAAgZALgTQAMgSAagRIAAgCQgIgIgEgKQgFgJABgKQgBgfAXgTQAWgTAkgBQAXAAAQAKQAQAJAAANQAAADgEAEQgEADgFAAIgPgFQgOgFgLAAQgQAAgJAKQgJAKAAARQAAAHACAGQADAFAEAGQAFADAJAEIALAFIAEABIACADQgBAFgGAIQgIAHgGAAIgJgCIgMgEQgMAJgFAOQgGANAAARQAAAlAYAYQAZAYAlAAQAfAAATgQQATgQAAgaQAAgQgHgLQgIgJgNAAQgOAAgJAIQgIAIAAAMIAAADIAAADIgCABIgEAAQgGAAgFgGQgEgEAAgKQAAgcBVgnIAFgCQAWgLAMgMQAMgMAAgNQgBgJgEgFQgFgFgKAAIgIACIgHAAQgEAAgDgDQgCgCAAgEQgBgJALgFQALgGAQAAQAVAAAMAMQAMAKAAAUQAAAYgVAUQgVAUgrAQQASAGAKAPQAJAOAAAUQAAAOgGAOQgGAOgLAMQgSATgaAKQgaAKgigBQg7AAgjgbg");
	this.shape_4.setTransform(24.5,80.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgOBkIgVgDIgFADIgGABIgEgBIgEgCQgGgGgGgPQgFgPgBgPQAAgGADgEQAEgFAFABQAJAAAJAPIAHAMQAGAHAKAFQAKAFAKAAQAOAAAHgHQAHgGAAgLQAAgRgfgPIgLgFQgfgPgKgMQgLgNAAgSQAAgaASgPQARgQAdAAIAMAAIAOADIAJgDIAGgBQAJgBAKAPQAIAQAAAQQAAAIgDADQgCAEgHAAQgEAAgEgEQgEgDgGgJQgHgMgIgFQgIgFgKAAQgLAAgHAGQgGAHAAAKQgBAIAIAIQAGAGAXANIADABQA2AZgBAfQABAbgVASQgVATgfgBg");
	this.shape_5.setTransform(-12,84.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_6.setTransform(-30.4,84.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhdCEQgKgDAAgJQAAgGAJgDIAJgFQAEgEACgPQABgQAAgwIAAgeQAAg1gBgPQgDgPgEgDIgIgDQgMgEAAgGQAAgFADgDQAEgEAHgDIAbgIQANgEAHAAQAFAAADADQADADAAAHIAAAJIAAAEIABABIAHgFIAHgFQANgJAKgFQAKgEAMAAQAkAAAXAaQAWAbAAAqQAAAtgZAeQgaAegnAAQgRAAgFgFQgHgFAAgHQAAgEADgEQADgDAGAAIAEABIAHABQAWAAANgSQANgSgBgdQAAghgOgUQgOgUgWAAQgTAAgLALQgMALAAAdIAAB6IABAUQABAHACADQADADAIACIAIACIAFAEIABAGQgBAHgKADQgMADgcAAQgcAAgJgDg");
	this.shape_7.setTransform(-52.6,88.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgiCKQgJgDAAgJQAAgGAJgEIAFgCQAFgDADgGQABgHAAgOIAAgNIAAgQIAAgUQAAgegBgJQgCgJgEgCIgJgDQgLgEAAgGQAAgFADgDQADgEAJgDIAdgJIATgEQAGAAACAEQACAEAAAIIAAAMIAAAJIgCAwIAAABIAAAwQAAASABAIQACAHAFACIAHAEQAKADAAAIQAAAHgKADQgKADgYAAQgdAAgKgDgAgXhhQgJgGABgLQAAgLAJgHQAJgIANAAQALAAAJAHQAIAHAAALQAAAKgJAIQgJAHgMAAQgNAAgIgHg");
	this.shape_8.setTransform(-69,80.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("Ag8BJQgcgdAAgpQAAgsAdgdQAdgeArAAQAfAAAXARQAWAQAAAXQAAAJgGAFQgGAGgKAAQgKAAgGgFQgGgEgGgQQgHgOgIgGQgGgFgNAAQgVAAgNARQgMAQAAAeQAAAiASAVQASAWAbAAQAJAAAJgDQAIgCAIgFIAHgGQALgIAFAAQAFAAACACQACADAAAEQAAAFgEAGQgEAHgGAGQgQANgQAGQgRAHgTAAQgnAAgbgcg");
	this.shape_9.setTransform(-84.2,84.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("Ag+BJQgcgdAAgpQAAgsAcgeQAdgdArAAQAlAAAWAVQAWAWAAAkQAAAMgEAEQgDADgPAAIhJAAQgHAAgDgDQgEgDAAgFQAAgFAEgDQADgDAHAAIAnAAIAKgBQACgCAAgEQAAgTgMgMQgNgNgRAAQgXAAgLAUQgLAUAAAcQAAAeAPAWQAQAWAXAAQAPAAAKgDQAJgEAKgGIAHgGQAJgHAGAAQAEAAADACQADADAAAEQAAAFgFAGQgFAHgIAHQgRAOgQAGQgPAGgTAAQgoAAgbgcg");
	this.shape_10.setTransform(-104.5,84.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AApBgQgSg9gOgNQgMgMgUAAQgPAAAAgMQAAgMAMAAQAgAAAPgNQAQgMAAgaQAAgagQgNQgQgNgdAAQgPAAgGACQgFACgCAGIgCARIgBAnIAABVIABA5QABAOAEADIAIAEQAMAEAAAIQAAAIgKAEQgLADgfAAQgeAAgKgDQgLgEAAgIQAAgIAMgFIAIgEQAEgDACgXQACgXAAg8IgChJQgBgcgDgDQgCgDgKgFQgKgEAAgHQAAgHAGgDQAFgEANAAIAqAAIAngBIAegBQAqAAAWATQAXASAAAiQAAAZgPATQgPASgbAIIAAACQAVAEAMANQAMAMAJAfIAFAUQAIAeALAAIAGgBIAHAAQADAAADADQADADAAAEQAAAJgLAGQgLAGgSAAQgnAAgNgug");
	this.shape_11.setTransform(-128.1,80.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgUA7QgEgCAAgDIAEgHIADgGIAMgVQAEgKAAgEIgBgFIgHgDQgKgEgEgHQgFgHAAgKQAAgNAIgIQAIgJAMAAQAMAAAJALQAIALAAASQAAANgFANQgGAOgMAVIgJAPQgFAFgDAAQgGAAgDgCg");
	this.shape_12.setTransform(111.4,49);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgOBkIgVgDIgFADIgGABIgEgBIgEgCQgHgGgFgPQgGgPAAgPQAAgGAEgEQADgFAFABQAIAAAKAPIAHAMQAGAHAKAFQAKAFALAAQANAAAHgHQAHgGAAgLQAAgRgfgPIgLgFQgegPgLgMQgLgNAAgSQAAgaASgPQARgQAcAAIANAAIANADIAKgDIAGgBQAJgBAKAPQAIAQAAAQQAAAIgCADQgEAEgFAAQgFAAgEgEQgFgDgFgJQgIgMgHgFQgIgFgKAAQgLAAgHAGQgGAHgBAKQAAAIAIAIQAGAGAXANIADABQA1AZAAAfQAAAbgUASQgVATgfgBg");
	this.shape_13.setTransform(97.1,38.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AhdCEQgKgDAAgJQAAgGAJgDIAKgFQADgEABgPQACgQAAgwIAAgeQAAg1gCgPQgBgPgFgDIgIgDQgNgEAAgGQAAgFAEgDQAEgEAHgDIAbgIQANgEAHAAQAFAAADADQACADAAAHIAAAJIABAEIABABIAHgFIAHgFQAMgJALgFQAKgEAMAAQAkAAAXAaQAWAbAAAqQAAAtgZAeQgZAegoAAQgQAAgGgFQgHgFAAgHQAAgEADgEQADgDAGAAIAFABIAGABQAVAAANgSQANgSABgdQgBghgOgUQgOgUgWAAQgTAAgLALQgMALAAAdIAAB6IABAUQABAHACADQADADAIACIAIACIAFAEIABAGQAAAHgMADQgLADgcAAQgcAAgJgDg");
	this.shape_14.setTransform(76.9,42.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgiCKQgJgDAAgJQAAgGAJgEIAGgCQAFgDACgGQACgHAAgOIgBgNIAAgQIAAgUQAAgegBgJQgCgJgEgCIgJgDQgLgEAAgGQgBgFAEgDQADgEAJgDIAdgJIATgEQAGAAADAEQABAEAAAIIAAAMIAAAJIgBAwIAAABIgBAwQAAASABAIQACAHAFACIAHAEQAKADAAAIQAAAHgKADQgJADgZAAQgdAAgKgDgAgXhhQgJgGABgLQgBgLAKgHQAJgIANAAQALAAAJAHQAIAHAAALQAAAKgJAIQgJAHgMAAQgNAAgIgHg");
	this.shape_15.setTransform(60.5,34.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgoCJQgLgDAAgJQAAgHALgEQAKgEACgDQACgEABgfIAChbIgBgzIgCgfQAAgFgEgCQgDgBgIAAIgIAAQgOAAgHADQgHADgGAHIgGANIgGANIgFAHQgEACgDAAQgGAAgDgFQgCgFAAgMQAAgaAGgPQAGgQAJAAIACAAQAPADAYAAIBxAAQAXAAAQgDIACAAQAJAAAGAQQAGAPAAAaQAAALgCAGQgDAFgGAAIgHgCIgFgHIgGgNIgGgNQgGgHgHgDQgIgDgNAAIgIAAQgIAAgDABQgEACAAAFIgCAfIgBAzIACBbQABAfACAEQACADAKAEQALAEAAAHQAAAJgLADQgLAEgeAAQgdAAgLgEg");
	this.shape_16.setTransform(42.5,34.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AhZB/QgIgHgBgMQAAgLAHgGQAHgHAJAAIAJABIAGAFIAFAHQAFAIAEAAQAJAAALgPQAKgOAAgPQAAgQgOggIgBgEIgghDIgSgmQgCgGgMgFQgHgDgCgDQgDgCAAgEQAAgJALgEQAKgCAcAAQAcAAAKACQAJADAAAIIgBAGIgDAEIgHADQgIADAAAEIAEAOIAPAmIAQAkQAFAKADAAQACAAAEgJIANgfIAOgmQAEgOAAgEQABgGgLgGQgLgGAAgGQAAgGAJgDQAIgDAWABQAYAAAHACQAIADAAAIQAAAHgLADIgIADQgKAGgMAgIgHAQIgYA9QggBQgUAYQgUAYgcAAQgOABgKgJg");
	this.shape_17.setTransform(9.8,42.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AAiBaIgKgKIgIAFQgYAQgXAAQgdAAgRgQQgSgRAAgaQAAggAXgQQAWgRApgBQAJABAFADQAFADAAAHQAAAKgNAAQgTABgMAIQgMAKAAAQQAAAQALAJQAKAJARAAQASAAAIgIQAIgJAAgTIAAhJQAAgSgIgIQgHgKgNAAQgJAAgIAEQgJAEgHAKIgEAEQgMAPgNAAQgIAAgEgFQgFgEAAgJQAAgSAXgNQAWgMAjAAQAVAAAPAGQAQAFAIALQAGAHACANQADALAAAcIAAA9QAAALACAGQABAFAEABIAGACQANADAAAHQAAAIgNAJQgNAHgSAAQgIAAgKgLg");
	this.shape_18.setTransform(-10.1,38.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AhUB1QgXgbAAgpQAAgvAbgdQAageApAAIANACQAGABAEAFQADAEAAAFQAAAKgNAAIgFAAIgFgBQgWAAgMASQgNARAAAfQAAAgAOAVQAOATAWABQATgBALgKQALgMAAgVIAAg1IAAhZQAAgNgCgFQgDgGgHgCIgFgBQgMgEAAgHQAAgFAFgDQAEgEAPgGIAWgGIASgCQAGAAADADQADAFAAAIIAAAKIgCB2IABBRQABATADACIAOAFQAKABAAAIQAAAJgcAJIgTAEIgPACQgFAAgDgDQgCgDAAgGIAAgKIgBgDIgBgBIgGADIgIAHQgMAJgKADQgLAFgMAAQgkAAgXgag");
	this.shape_19.setTransform(-31.5,34.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("AghCKQgKgDAAgJQAAgGAKgEIAEgCQAFgDADgGQABgHAAgOIAAgNIAAgQIAAgUQAAgegBgJQgCgJgEgCIgJgDQgMgEAAgGQABgFADgDQAEgEAIgDIAdgJIATgEQAGAAACAEQACAEAAAIIAAAMIAAAJIgCAwIAAABIAAAwQAAASABAIQADAHAEACIAHAEQAKADAAAIQAAAHgKADQgJADgZAAQgdAAgJgDgAgXhhQgIgGAAgLQAAgLAJgHQAJgIANAAQALAAAJAHQAIAHAAALQAAAKgJAIQgJAHgNAAQgMAAgIgHg");
	this.shape_20.setTransform(-49.1,34.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("AggCLQgKgEAAgIQABgGAHgEIAKgFQAEgDACgMIAAgmIAAgeIAAgkIAAgOQAAgxgBgOQgCgOgEgCIgMgFQgNgDAAgHQABgFAEgDQADgEAOgEIAagHIATgDQAGAAADAEQABADAAAJIAAAPQgCBFAABFIABBCQABAOADAEIAMAFQAIAEABAHQAAAIgKADQgKADgZAAQgcAAgKgDg");
	this.shape_21.setTransform(-60.2,34.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("AhGBIQgbgcAAgrQAAgrAdgdQAdgdAqAAQAqAAAbAbQAaAbAAArQAAAsgcAeQgdAegpAAQgqAAgcgdgAgkg5QgMAQAAAaQAAAlAQAaQAQAaAXAAQATAAAMgQQALgQAAgbQAAgkgPgaQgSgagWAAQgSAAgMAQg");
	this.shape_22.setTransform(-76.2,38.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("AArCIQgKgEAAgIQAAgIALgFIAJgDQADgDABgMIACguIAAgbIgCgHQgCgEgKgBQgJgBgkAAIgpABQgKABgDACIgDAGIAAAOIAAAQIABAuQABAMADADIAIADQAMAFAAAIQABAIgLAEQgLADgeAAQgfAAgKgDQgLgEAAgIQAAgHAMgGIAIgDQAFgDACgZQABgYAAg6IgBhIQgCgcgDgEQgCgDgKgEQgKgFAAgHQAAgIAJgCQAIgDAjgBQAiABAIADQAJACAAAIQAAAIgMAEIgIAFQgEACAAAMIgCA5QAAAIAHADQAIACAbAAIAQAAIApgBQALgBAEgDIADgEIAAgHIAAgJIgCgvQgBgKgDgCIgJgFQgLgEAAgIQAAgIAJgCQAIgDAigBQAjABAIADQAJACAAAIQAAAIgMAEIgIAFQgEACgDAaQgBAaAAA0IABBKQACAdADAFQACACAKAEQAKAFAAAHQAAAIgLAEQgKADgfAAQgfAAgKgDg");
	this.shape_23.setTransform(-101.6,34.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.classicturkeydinner, new cjs.Rectangle(-144.4,9.4,288.9,95.8), null);


(lib.seventeenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// rectangle
	this.instance = new lib.seventeenvideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-73.7,-29.2,147.5,38.4);


(lib.fourteentableuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteentable();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentableuse, new cjs.Rectangle(-160,-240,320,480), null);


// stage content:
(lib.interstitialfourteen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_44 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_226 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(44).call(this.frame_44).wait(182).call(this.frame_226).wait(4));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.4,240.1,1.553,0.731,0,0,0,0.2,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(230));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(230));

	// white-fade
	this.instance_1 = new lib.whiterectanglefadeone();
	this.instance_1.parent = this;
	this.instance_1.setTransform(161.5,239);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(221));

	// kale-logo
	this.instance_2 = new lib.kalelogo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(160.1,37);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.09,scaleY:0.09},0).to({scaleX:1.08,scaleY:1.08,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).wait(208));

	// order-now
	this.instance_3 = new lib.ordernow();
	this.instance_3.parent = this;
	this.instance_3.setTransform(157,293.1);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(44).to({y:291.6},0).to({alpha:1},10).wait(176));

	// cta-rollover
	this.cta_rollover = new lib.seventeenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(160,294);
	this.cta_rollover.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(44).to({alpha:1},10).wait(176));

	// cta-rectangle
	this.instance_4 = new lib.seventeenrectangle();
	this.instance_4.parent = this;
	this.instance_4.setTransform(160,294);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(44).to({alpha:1},10).wait(176));

	// main-and-sides
	this.instance_5 = new lib.mainsidesforeight();
	this.instance_5.parent = this;
	this.instance_5.setTransform(160,232.5);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(194).to({alpha:1},10).wait(26));

	// classic-turkey-meal
	this.instance_6 = new lib.classicturkeydinner();
	this.instance_6.parent = this;
	this.instance_6.setTransform(160,158.8);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(208).to({y:149.8},0).to({alpha:1},10).wait(12));

	// top-left
	this.instance_7 = new lib.fourteentopleft();
	this.instance_7.parent = this;
	this.instance_7.setTransform(95,69.5);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(9).to({alpha:1},10).wait(211));

	// rop-right
	this.instance_8 = new lib.fourteentopright();
	this.instance_8.parent = this;
	this.instance_8.setTransform(270.5,63.5);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(24).to({alpha:1},10).wait(196));

	// bottom-right
	this.instance_9 = new lib.fourteenbottomright();
	this.instance_9.parent = this;
	this.instance_9.setTransform(206.5,377);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(14).to({alpha:1},10).wait(206));

	// bottom-left
	this.instance_10 = new lib.fourteenbottomleft();
	this.instance_10.parent = this;
	this.instance_10.setTransform(47.5,394.5);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(19).to({alpha:1},10).wait(201));

	// sweet-inspiration
	this.instance_11 = new lib.swetinspiration();
	this.instance_11.parent = this;
	this.instance_11.setTransform(164.2,191.7);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(134).to({alpha:1},10).wait(40).to({alpha:0},5).wait(41));

	// holiday-hosting-tips
	this.instance_12 = new lib.holidayhosting();
	this.instance_12.parent = this;
	this.instance_12.setTransform(160,191.7);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(84).to({alpha:1},10).wait(40).to({alpha:0},5).wait(91));

	// party-ready-recipes
	this.instance_13 = new lib.partyreadyrecipes();
	this.instance_13.parent = this;
	this.instance_13.setTransform(160,191.7);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(34).to({alpha:1},10).wait(40).to({alpha:0},5).wait(141));

	// berries
	this.instance_14 = new lib.seventeenberries_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(277,47.5);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(94).to({alpha:1},10).wait(126));

	// table
	this.instance_15 = new lib.fourteentableuse();
	this.instance_15.parent = this;
	this.instance_15.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(230));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(154.1,230,335,496);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 480,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/seventeenberries.png", id:"seventeenberries"},
		{src:"images/index_atlas_NP_.jpg", id:"index_atlas_NP_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;